### ISSUE TITLE
Uncaught TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by ghost** [AshesOfOwls/jquery.shapeshift#33] opened 2013-04-29 07:53 UTC
The console gives me the error, "Uncaught TypeError: Cannot read property 'left' of undefined", whenever I try to drag the last child. For example, when I try to drag "Child Element 3" in:

``` html
<div class="container">
    <div>Child Element 1</div>
    <div>Child Element 2</div>
    <div>Child Element 3</div>
</div>
```

However, I do not get this error when I only have 2 child elements.

This is the CSS:

``` css
.container {
    position: relative;
    width: 100%;
    border: 1px solid #aaa;
}

.container div {
    position: absolute;
    height: 100px;
    width: 100px;
    border: 1px solid #aaa;
    cursor: move;
}
```

This is the JS:

``` javascript
jQuery(function ($) {
    $('.container').shapeshift();
});
```

**Comment by AshesOfOwls** [comment] 2013-04-29 18:18
I don't see anything blaring of the top of my head, will look into this tonight.

**Comment by jpellerin** [comment] 2013-04-29 20:33
I've seen this too, also with three or more elements. The error is thrown in a couple of places, the first being the drag handler Line 509 (in the coffeescript):

```
ui.position.left = e.pageX - $selected.parent().offset().left - selected_offset_x;
```

Apparently sometimes $selected.parent() doesn't resolve to something with an .offset() -- but only for the last element. It's easily reproducible by dragging the 3rd element anywhere, or dragging the first element into the placeholder that takes the place of the 3rd element when the 1st is dragged that way -- in that case, the 3rd element also permanently disappears.

**Comment by AshesOfOwls** [comment] 2013-04-29 20:41
Thanks jpellerin, that helps a lot

**Comment by jpellerin** [comment] 2013-04-29 20:52
One correction, it's actually the dragged (1st) element that disappears -- a drag placeholder (.ss-placeholder-child) remains in the place of the 3rd element.

**Comment by AshesOfOwls** [comment] 2013-04-29 22:05
I'm tearing my hair out trying to replicate the example, across the major browsers it seems to be working for me.

I set up an issues branch on Shapeshift to set up some demos to help with these processes. I set a working example (at least for me) for this issue up here: https://github.com/McPants/jquery.shapeshift/tree/issues/issue33

Could you clone this and see if the same error appears?

There is a workaround for this in the meantime though. All that code is doing is centering the element around the cursor so if you just remove the entire ui.position lines and it shouldn't give you that error in your instance. In the future I am going to add an option to determine the cursor vs element positioning while dragging so solving this problem will be advantageous for that.

**Comment by jpellerin** [comment] 2013-04-30 00:08
Looking at the demo vs my app I see some differences  -- shapeshift demo
has jquery 2.0 and jquery ui 1.9.1, I have jquery 1.8.3 and a custom build
of ui 1.10.2 with only draggable and effects. I also have bootstrap 2.3.1,
same as the demo, but my load order is different -- bootstrap after
shapeshift rather than before. When I'm back at work tomorrow I'll try
changing those all around to match the demo (one at a time) and see if
anything makes a difference.

**Comment by ghost** [comment] 2013-04-30 00:19
I FOUND THE ISSUE :) its the jQuery version. I've been playing with this http://jsfiddle.net/Amghn/ and, when i switch the jQuery library to 1.8.3, the issue comes up. Shapeshift will work for later versions of jQuery though. 

But i didn't realise my jQuery version wasn't up to date while I was developing because I was relying on the jQuery library that comes with Wordpress and I assumed it would have been xD

**Comment by jpellerin** [comment] 2013-04-30 13:15
Confirmed here too. Changed to jquery 2.0, dragging works properly with 3
items.

**Comment by AshesOfOwls** [comment] 2013-04-30 17:01
Awesome! Cool if I close this issue?

**Comment by jpellerin** [comment] 2013-04-30 17:36
:+1: to closing the issue, the README update covers it I think.

**Comment by AshesOfOwls** [comment] 2013-04-30 17:46
Thanks for the help

**Closed as completed** 2013-04-30 17:45 UTC
